#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_A, KC_R, LGUI_T(KC_S), LALT_T(KC_T), KC_G, KC_M, LALT_T(KC_N), LGUI_T(KC_E), KC_I, KC_O, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_LCTL), OSM(MOD_LSFT), KC_SPC, TG(1)),
	[1] = LAYOUT_split_3x5_2(KC_ESC, KC_LBRC, KC_RBRC, KC_BSLS, KC_NO, KC_EQL, KC_7, KC_8, KC_9, KC_BSPC, KC_GRV, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_MINS, KC_4, KC_5, KC_6, KC_ENT, KC_TAB, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_0, KC_1, KC_2, KC_3, KC_QUOT, OSM(MOD_LCTL), OSM(MOD_LSFT), TG(0), TG(2)),
	[2] = LAYOUT_split_3x5_2(QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




